### PR TITLE
adds the ability to have an imsmanifest.xml per course

### PR DESCRIPTION
**Pull request by moloko**

### CODE REVIEW

**Comment by moloko** [comment]
@taylortom there's actually lots more changes here than just multiple-manifest work - do you think all this is safe to put into master now?

**Comment by taylortom** [comment]
Should be, @danielghost has definitely used the plugin exclusion in at least one live course. Once it gets the green light, it can go into the [adapt_framework](https://github.com/cgkineo/adapt_framework) fork.

**Comment by moloko** [comment]
Who needs to give green light?

On 6 January 2015 at 16:25, Tom Taylor <notifications@github.com> wrote:

> Should be, @danielghost <https://github.com/danielghost> has definitely
> used the plugin exclusion in at least one live course. Once it gets the
> green light, it can go into the adapt_framework
> <https://github.com/cgkineo/adapt_framework> fork.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgkineo/adapt-grunt/pull/19#issuecomment-68888599>.
>



-- 
--------------------------------------------------------------------------------------------------------------------------------
IMPORTANT: This email is intended for the use of the individual
addressee(s) named above and may contain information that is confidential,
privileged, or unsuitable for overly sensitive persons with low
self-esteem, no sense of humour, or irrational religious beliefs.
If you have received this email in error, please add some egg whites and
nutmeg, whisk and place in a warm oven for 40 minutes.

**Comment by taylortom** [comment]
Well it's an internal thing, so we can be wild reckless and just add it. It's one of those things that needs to be tested on live projects really, and the devs are really good at giving feedback if anything goes wrong.

**Pull request merged**
